# Generated by Django 5.0.6 on 2024-07-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_fullname_clients_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='idClient',
            new_name='idClientAddress',
        ),
        migrations.AddField(
            model_name='clients',
            name='secondLastname',
            field=models.CharField(default='\u200e ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='secondName',
            field=models.CharField(default='\u200e ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
