# Generated by Django 5.0.6 on 2024-07-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_idclient_clients_idclientaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='secondLastname',
            field=models.CharField(default='\u200e ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='secondName',
            field=models.CharField(default='\u200e ', max_length=50),
            preserve_default=False,
        ),
    ]
