# Generated by Django 5.0.6 on 2024-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contacts_secondlastname_contacts_secondname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='secondLastname',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='secondName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='secondLastName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
